  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.4.0
    user: root
    environment:
      - GITSYNC_REPO=GIT_REPO_URL
      - GITSYNC_REF=ADDONS_BRANCH
      - GITSYNC_ROOT=/git
      - GITSYNC_LINK=current
      - GITSYNC_PERIOD=60s
      - GITSYNC_SSH_KEY_FILE=/etc/git-secret/ssh
      - GITSYNC_SSH_KNOWN_HOSTS=false
      - GIT_SSH_COMMAND=ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    volumes:
      - ./addons:/git
      - ./keys/deploy_key:/etc/git-secret/ssh:ro
    restart: always
